const components = ["belt", "bow", "chain", "cloak", "glove", "rod", "sword", "tear"];
const itemTable = new Map([
  ["belt", new Map([
    ["belt", "Warmog's Armor"],
    ["bow", "Nashor's Tooth"],
    ["chain", "Sunfire Cape"],
    ["cloak", "Evenshroud"],
    ["glove", "Striker's Flail"],
    ["rod", "Morellonimicon"],
    ["sword", "Sterak's Gage"],
    ["tear", "Sprit Visage"],
  ])],
  ["bow", new Map([
    ["belt", "Nashor's Tooth"],
    ["bow", "Red Buff"],
    ["chain", "Titan's Resolve"],
    ["cloak", "Kraken's Fury"],
    ["glove", "Last Whisper"],
    ["rod", "Guinsoo's Rageblade"],
    ["sword", "Giant Slayer"],
    ["tear", "Void Staff"],
  ])],
  ["chain", new Map([
    ["belt", "Sunfire Vest"],
    ["bow", "Titan's Resolve"],
    ["chain", "Bramble Vest"],
    ["cloak", "Gargoyle's Stoneplate"],
    ["glove", "Steadfast Heart"],
    ["rod", "Crownguard"],
    ["sword", "Edge of Night"],
    ["tear", "Protector's Vow"],
  ])],
  ["cloak", new Map([
    ["belt", "Evenshroud"],
    ["bow", "Kraken's Fury"],
    ["chain", "Gargoyle's Stoneplate"],
    ["cloak", "Dragon's Claw"],
    ["glove", "Quicksilver"],
    ["rod", "Ionic Spark"],
    ["sword", "Bloodthirster"],
    ["tear", "Adaptive Helm"],
  ])],
  ["glove", new Map([
    ["belt", "Striker's Flail"],
    ["bow", "Last Whisper"],
    ["chain", "Steadfast Heart"],
    ["cloak", "Quicksilver"],
    ["glove", "Theif's Gloves"],
    ["rod", "Jeweled Gauntlet"],
    ["sword", "Infinity Edge"],
    ["tear", "Hand of Justice"],
  ])],
  ["rod", new Map([
    ["belt", "Morellonimicon"],
    ["bow", "Guinsoo's Rageblade"],
    ["chain", "Crownguard"],
    ["cloak", "Ionic Spark"],
    ["glove", "Jeweled Gauntlet"],
    ["rod", "Rabadon's Deathcap"],
    ["sword", "Hextech Gunblade"],
    ["tear", "Archangel's Staff"],
  ])],
  ["sword", new Map([
    ["belt", "Sterak's Gage"],
    ["bow", "Giant Slayer"],
    ["chain", "Edge of Night"],
    ["cloak", "Bloodthirster"],
    ["glove", "Infinity Edge"],
    ["rod", "Hextech Gunblade"],
    ["sword", "Deathblade"],
    ["tear", "Spear of Shojin"],
  ])],
  ["tear", new Map([
    ["belt", "Spirit Visage"],
    ["bow", "Void Staff"],
    ["chain", "Protector's Vow"],
    ["cloak", "Adaptive Helm"],
    ["glove", "Hand of Justice"],
    ["rod", "Archangel's Staff"],
    ["sword", "Spear of Shojin"],
    ["tear", "Blue Buff"],
  ])],
]);

export default {
  components, 
  itemTable
};
