import names from "../constants/names.js";

export const components = new Map([
  ["belt", names.ITEM_COMPONENT_GIANTS_BELT],
  ["bow", names.ITEM_COMPONENT_RECURVE_BOW],
  ["chain", names.ITEM_COMPONENT_CHAIN_VEST],
  ["cloak", names.ITEM_COMPONENT_NEGATRON_CLOAK],
  ["glove", names.ITEM_COMPONENT_SPARRING_GLOVES],
  ["rod", names.ITEM_COMPONENT_NEEDLESSLY_LARGE_ROD],
  ["sword", names.ITEM_COMPONENT_BF_SWORD],
  ["tear", names.ITEM_COMPONENT_TEAR_OF_THE_GODDESS],
]);

export const itemTable = new Map([
  ["belt", new Map([
    ["belt", names.ITEM_WARMOGS_ARMOR],
    ["bow", names.ITEM_NASHORS_TOOTH],
    ["chain", names.ITEM_SUNFIRE_CAPE],
    ["cloak", names.ITEM_EVENSHROUD],
    ["glove", names.ITEM_STRIKERS_FLAIL],
    ["rod", names.ITEM_MORELLONOMICON],
    ["sword", names.ITEM_STERAKS_GAGE],
    ["tear", names.ITEM_SPIRIT_VISAGE],
  ])],
  ["bow", new Map([
    ["belt", names.ITEM_NASHORS_TOOTH],
    ["bow", names.ITEM_RED_BUFF],
    ["chain", names.ITEM_TITANS_RESOLVE],
    ["cloak", names.ITEM_KRAKENS_FURY],
    ["glove", names.ITEM_LAST_WHISPER],
    ["rod", names.ITEM_GUINSOOS_RAGEBLADE],
    ["sword", names.ITEM_GIANT_SLAYER],
    ["tear", names.ITEM_VOID_STAFF],
  ])],
  ["chain", new Map([
    ["belt", names.ITEM_SUNFIRE_CAPE],
    ["bow", names.ITEM_TITANS_RESOLVE],
    ["chain", names.ITEM_BRAMBLE_VEST],
    ["cloak", names.ITEM_GARGOYLE_STONEPLATE],
    ["glove", names.ITEM_STEADFAST_HEART],
    ["rod", names.ITEM_CROWNGUARD],
    ["sword", names.ITEM_EDGE_OF_NIGHT],
    ["tear", names.ITEM_PROTECTORS_VOW],
  ])],
  ["cloak", new Map([
    ["belt", names.ITEM_EVENSHROUD],
    ["bow", names.ITEM_KRAKENS_FURY],
    ["chain", names.ITEM_GARGOYLE_STONEPLATE],
    ["cloak", names.ITEM_DRAGONS_CLAW],
    ["glove", names.ITEM_QUICKSILVER],
    ["rod", names.ITEM_IONIC_SPARK],
    ["sword", names.ITEM_BLOODTHIRSTER],
    ["tear", names.ITEM_ADAPTIVE_HELM],
  ])],
  ["glove", new Map([
    ["belt", names.ITEM_STRIKERS_FLAIL],
    ["bow", names.ITEM_LAST_WHISPER],
    ["chain", names.ITEM_STEADFAST_HEART],
    ["cloak", names.ITEM_QUICKSILVER],
    ["glove", names.ITEM_THIEFS_GLOVES],
    ["rod", names.ITEM_JEWELED_GAUNTLET],
    ["sword", names.ITEM_INFINITY_EDGE],
    ["tear", names.ITEM_HAND_OF_JUSTICE],
  ])],
  ["rod", new Map([
    ["belt", names.ITEM_MORELLONOMICON],
    ["bow", names.ITEM_GUINSOOS_RAGEBLADE],
    ["chain", names.ITEM_CROWNGUARD],
    ["cloak", names.ITEM_IONIC_SPARK],
    ["glove", names.ITEM_JEWELED_GAUNTLET],
    ["rod", names.ITEM_RABADONS_DEATHCAP],
    ["sword", names.ITEM_HEXTECH_GUNBLADE],
    ["tear", names.ITEM_ARCHANGELS_STAFF],
  ])],
  ["sword", new Map([
    ["belt", names.ITEM_STERAKS_GAGE],
    ["bow", names.ITEM_GIANT_SLAYER],
    ["chain", names.ITEM_EDGE_OF_NIGHT],
    ["cloak", names.ITEM_BLOODTHIRSTER],
    ["glove", names.ITEM_INFINITY_EDGE],
    ["rod", names.ITEM_HEXTECH_GUNBLADE],
    ["sword", names.ITEM_DEATHBLADE],
    ["tear", names.ITEM_SPEAR_OF_SHOJIN],
  ])],
  ["tear", new Map([
    ["belt", names.ITEM_SPIRIT_VISAGE],
    ["bow", names.ITEM_VOID_STAFF],
    ["chain", names.ITEM_PROTECTORS_VOW],
    ["cloak", names.ITEM_ADAPTIVE_HELM],
    ["glove", names.ITEM_HAND_OF_JUSTICE],
    ["rod", names.ITEM_ARCHANGELS_STAFF],
    ["sword", names.ITEM_SPEAR_OF_SHOJIN],
    ["tear", names.ITEM_BLUE_BUFF],
  ])],
]);

export default {
  components,
  itemTable,
};
